### ISSUE TITLE
InvalidOperationException while using the Tool

### ISSUE THREAD

**Issue by iancbogue** [kianzarrin/LoadOrder#6]
I received this error while I was resubscribing to broken mods/assets:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at LoadOrderTool.UI.LoadOrderWindow.DTO2Cache(PublishedFileDTO[] dtos) in \UI\LoadOrderWindow.cs:line 787
   at LoadOrderTool.UI.LoadOrderWindow.<>c__DisplayClass76_0.<CacheWSDetails>b__0() in \UI\LoadOrderWindow.cs:line 755
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at LoadOrderTool.UI.LoadOrderWindow.CacheWSDetails(Boolean save) in \UI\LoadOrderWindow.cs:line 760
	-- LoadOrderTool:end of inner stack trace --
   at LoadOrderTool.LogExtensions.Log(Exception ex, Boolean showInPanel) in \Util\Log.cs:line 252
   at LoadOrderTool.UI.LoadOrderWindow.CacheWSDetails(Boolean save) in \UI\LoadOrderWindow.cs:line 760
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at LoadOrderTool.Program.Main() in \Program.cs:line 75

Here is my log file:
[LoadOrderTool.log](https://github.com/kianzarrin/LoadOrder/files/7431727/LoadOrderTool.log)

**Comment by kianzarrin** [comment]
is this resolved now?

**Comment by iancbogue** [comment]
For all intents and purposes, yes. I stopped being able to play Cities on a regular basis so I haven't used the mod in a long time.
