### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by aubergine10** [kianzarrin/LoadOrder#8]
Just started using LOM and when clicking the `Startup` tab get this error:

![image](https://user-images.githubusercontent.com/1386719/156464166-a1f0a14a-9af3-4eb5-993d-2349469c717e.png)

```
[Error]  282,990ms | gap=198,125ms | '' not found.
   at KianCommons.Log.Error(System.String message, Boolean copyToGameLog)
   at KianCommons.Log.Error(System.String message, Boolean copyToGameLog)
   at KianCommons.Prompt.Error(System.String title, System.String message)
   at LoadOrderMod.Settings.Tabs.SubscriptionsTab.CheckSteamPath(System.String path)
   at LoadOrderMod.Settings.Tabs.SubscriptionsTab+<>c.<Make>b__5_4(System.String text)
   at UIHelper+<AddTextfield>c__AnonStorey3.<>m__1(ColossalFramework.UI.UIComponent c, System.String sel)
   at ColossalFramework.UI.UITextField.OnSubmit()
   at ColossalFramework.UI.UITextField.OnLostFocus(ColossalFramework.UI.UIFocusEventParameter p)
   at ColossalFramework.UI.UIView.SetFocus(ColossalFramework.UI.UIComponent component)
   at ColossalFramework.UI.UIComponent.Focus()
   at ColossalFramework.UI.UIComponent.OnMouseDown(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIButton.OnMouseDown(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput(IInputTranslator translator, Ray ray, ColossalFramework.UI.UIComponent component, Boolean retainFocusSetting)
   at ColossalFramework.UI.UIInput.ProcessMouseInput()
   at ColossalFramework.UI.UIInput.FpsBoosterUpdate()
   at BehaviourUpdater.UiInputUpdater.UpdateInput()
   at BehaviourUpdater.Updater.Update()
```
[output_log.txt](https://github.com/kianzarrin/LoadOrder/files/8173497/output_log.txt)

Looks like it's due to blank start-up path in `Subscriptions` tab maybe?

![image](https://user-images.githubusercontent.com/1386719/156464354-4b1692bd-8786-4db1-8dbc-266cf2eed7ef.png)

Also, Paradox Account panel is gone from main menu (not sure if caused by LOM or Control It - however neither mod mentions that it removes the account panel).

**Comment by aubergine10** [comment]
[LoadOrderTool.log](https://github.com/kianzarrin/LoadOrder/files/8173530/LoadOrderTool.log)
[LoadOrder.log](https://github.com/kianzarrin/LoadOrder/files/8173531/LoadOrder.log)
[LoadOrderIPatch.log](https://github.com/kianzarrin/LoadOrder/files/8173533/LoadOrderIPatch.log)

**Comment by kianzarrin** [comment]
if you could go to startup you could show ad. panels.
![image](https://user-images.githubusercontent.com/26344691/156526755-a8ff467b-d5fb-4536-bf8d-ddfdb7b2a74a.png)

**Comment by kianzarrin** [comment]
@aubergine10 you still can go to startup right?

if you click on that text box and click out of it (eg: pressing another tab) then the text value is evaluated (see `OnSubmit()` from your stack trace). if the value is invalid it gives error that path does not exit. that is expected.
`OnSubmit()` is called if you click out or if you press enter.

**Comment by kianzarrin** [comment]
So can we close this issue?

**Comment by aubergine10** [comment]
Ah, I didn't expect `ad panels` to incude `account login panel`. A better checkbox label might be `remove ad and login panels` (or just leave that stuff to `Control It` / `Hide It, Bobby` mods).

And yes, I could still access the startup tab after closing the error panel.

**Comment by kianzarrin** [comment]
its an advert disguised as login :)

**Comment by aubergine10** [comment]
users don't know that
